env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:vue/essential"
  - "@nuxtjs/eslint-config-typescript"
  - "eslint-config-prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {}
